---

version: '3.8'
services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wishlist
      MYSQL_USER: mamiko
      MYSQL_PASSWORD: mamikoprogram
    volumes:
      - ./mysql/data:/var/lib/mysql
  php:
    build: ./php
    depends_on:
      - db
    ports:
      - 8080:8000
    volumes:
      - ./work:/work
